version: '3.8'

services:
  qbt-filebot-renamer:
    build: .
    container_name: qbt-filebot-renamer
    ports:
      - "${HOST_PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    volumes:
      - ${DOWNLOADS_PATH:-./downloads}:/downloads:ro
      - ${FILEBOT_DATA_PATH:-./filebot-data}:/filebot
      - ${FILEBOT_LICENSE_FILE}:/filebot/license.psm:ro
    restart: unless-stopped
    networks:
      - qbt-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  qbt-network:
    driver: bridge